services:
  - type: web
    name: transaction-processor
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r build-requirements.txt
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
